version: "3"

services:
  qa-monitor:
    image: "${AWS_ECR_URL}/${IMAGE_NAME}:${ECR_TAG}"
    container_name: "${IMAGE_NAME}-container"
    restart: unless-stopped
    ports:
      - 9015:3005
    env_file:
      - ./.env